In [ ]:
# CREATE a table called movies with at least 8 datasets such as movie_id, title, genre, year, imdb_ratings, and country
#  1. Select all movies with a rating higher than 8.5.
#  2. Find the titles of all movies released between 2000 and 2020.
#  3. List distinct genres from the movies table.
#  4. Find all movies whose titles start with 'I'.
#  5. Show all movies where the country is NOT 'USA'.
#  6. List all movies where genre is 'Thriller' OR imdb_rating is above 9.
#  7. Find movies that have NULL country values.
#  8. Get all movies ordered by imdb_rating descending.
#  9. Show title as 'Movie Name' and genre as 'Category' for all movies.
# 10. Find all movies where the title ends with the letter 'r'.

# creating table with movies 

CREATE TABLE movies (
    movie_id INTEGER PRIMARY KEY,
    title  TEXT UNIQUE,
    genre TEXT  NOT NULL,
    year  INTEGER NOT NULL,
    imdb_rating REAL,
    country   TEXT
);

# inserting dataset into the tables

INSERT INTO movies(movie_id, title, genre, year, imdb_rating, country)
values
(1, 'Inception',    'Sci-Fi',   2010,   8.8,    'USA'),
(2, 'Titanic',  'Romance',  1997,   7.8,    'USA'),
(3, 'Parasite',     'Thriller',     2019,   8.6,  'South Korea'),
(4, 'The Godfather', 'Crime'    1972,   9.2,    'USA'),
(5, 'Spirited Away',  'Animation',  2001,   8.6,    'Japan')
(6, 'Joker',	'Drama',	2019,	8.4, 	'USA' )
(7, 'Oldboy'	'Thriller'	2003,	8.4,	'South Korea')
(8, 'Interstellar'	Sci-Fi	2014,	8.6,	 'USA')
(9, 'Cinema Paradiso', 'Drama', 1988, NULL, NULL)
(10, 'Whiplash', 'Drama', 2014, 8.5, 'NULL');


# selecting movies rating higher than 8.5
SELECT *
FROM movies
WHERE imdb_rating > 8.5;


# find titles of movies released between 2000 and 2020
SELECT *
FROM movies
WHERE year BETWEEN 2000 AND 2020;


# list distinct genre from the movie table
SELECT DISTINCT genre
FROM movies;

# Find all movies whose titles start with 'I'.
SELECT *
FROM movies
WHERE title LIKE 'I%';

# Show all movies where the country is NOT 'USA'.
SELECT *
FROM movies
WHERE country != 'USA';

# List all movies where genre is 'Thriller' OR imdb_rating is above 9.
SELECT *
FROM movies
WHERE genre = 'Thriller' 
OR imdb_rating > 9;

# Find movies that have NULL country values.
SELECT *
FROM movies
WHERE country IS NULL;


# Get all movies ordered by imdb_rating descending.
SELECT *
FROM movies
ORDER BY imdb_rating DESC;

# Show title as 'Movie Name' and genre as 'Category' for all movies.
SELECT title 
AS 'Movie Name',
genre AS 'Category'
FROM movies;


# find all the movies that ends with letter 'r'.
SELECT *
FROM movies
WHERE title LIKE '%r';